# Generated by Django 3.0.8 on 2021-01-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='phone',
        ),
        migrations.AddField(
            model_name='orders',
            name='phone_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
