# Generated by Django 3.0.8 on 2021-02-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_selling_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerproductstock',
            old_name='product_pc',
            new_name='product_ps',
        ),
        migrations.RenameField(
            model_name='sellerproductstock',
            old_name='seller_pc',
            new_name='seller_ps',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='phone',
        ),
        migrations.AddField(
            model_name='orders',
            name='phone_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
