# Generated by Django 3.0.8 on 2021-02-05 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210204_1723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerProductStock',
        ),
    ]
