# Generated by Django 3.0.8 on 2021-02-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210127_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerproductstock',
            old_name='product_pc',
            new_name='product_ps',
        ),
        migrations.RenameField(
            model_name='sellerproductstock',
            old_name='seller_pc',
            new_name='seller_ps',
        ),
        migrations.AddField(
            model_name='product',
            name='barcode_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(blank=True, max_length=111, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zip_code',
            field=models.CharField(blank=True, max_length=111, null=True),
        ),
    ]
