# Generated by Django 3.0.8 on 2021-01-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210127_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerproductstock',
            old_name='product_pc',
            new_name='product_ps',
        ),
        migrations.RenameField(
            model_name='sellerproductstock',
            old_name='seller_pc',
            new_name='seller_ps',
        ),
    ]
