# Generated by Django 3.0.8 on 2021-02-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_delete_sellerproductstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode_number',
            field=models.CharField(default='', max_length=30),
        ),
    ]
